### ISSUE TITLE
Controls stealing touch gesture key-up events

### ISSUE THREAD

**Issue by t-muko** [openlayers/openlayers#11251]
**Describe the bug**
When pinch zooming gesture ends on top of control, the gesture control gets messed up. Somehow there seems to be now an extra finger in the position where the last finger was released on top of the control and attempted panning will produce zooming or rotation

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/bing-maps.html' with a touch enabled device. (tested with a phone, tablet and Win 10 touch enabled desktop PC running Firefox)
2. Pinch zoom-in on the map so that one finger slides on top of control such as zoom buttons. Lift up this finger last.
3. After lifting both fingers, try to pan the map with one finger.

**Expected behavior**
After zooming, the map operation would be normal

The behaviour seems to be somehow related to timing and it seems to be easier to replace with slightly heavier tile maps such as satellite maps or high resolution terrain maps.
The feature is very annoying on small screens, such as mobile phones, when you have multiple controls such as zoom slider, attributions and scale line visible on the edges of the screen. In such situations this issue will hit you very quickly. I have done most of my testing with zoom slider, but managed to repeat the issue with zoom buttons and attributions area.

Setting touch-events to none on the control's css (such as attribution or scale line), the problem can be avoided but of course this does not work for interactions.

**Comment by ahocevar** [comment]
This issue should be fixed on the main branch. See https://openlayers.org/en/main/examples/bing-maps.html

**Comment by t-muko** [comment]
> 
> 
> This issue should be fixed on the main branch. See https://openlayers.org/en/main/examples/bing-maps.html

I can still replicate the error using the above mentioned link on PC. I was not able to replicate the problem on a mobile Chrome, though.

I also upgraded my map app to 6.3.1 and still having the issue in the mobile there too.

**Comment by ahocevar** [comment]
6.3.1 does not contain that fix. In your application, `npm install ol@dev` to get the latest version with the fix.

For the issue on the touch enabled PC, which version of Firefox are you using?

**Comment by t-muko** [comment]
Tested with touch enabled Win10 Firefox 77.0.1 and 78.0.1. Both showing the unwanted behaviour on https://openlayers.org/en/main/examples/bing-maps.html. 
Chrome 83.0.4103.116 seems to work without problems.

**Comment by t-muko** [comment]
Tested ol@6.3.2-dev.1594067850955 with my own map app. 
The problem is still there with all tested browsers: Chrome and Firefox on PC as well as on Android (Chrome) Webview, Chrome browser and Samsung internet browser.

**Comment by ahocevar** [comment]
I have tried to reproduce this issue, but I'm failing to.

@t-muko You mentioned

> Setting touch-events to none on the control's css (such as attribution or scale line), the problem can be avoided but of course this does not work for interactions.

Would you be able to share your code with that workaround? Do you mean `pointer-events: none`?

**Comment by t-muko** [comment]
You can test the issue with this: [https://beta--karttahimmeli.netlify.app/](https://beta--karttahimmeli.netlify.app/).
The problem does not occur on the coarse zoom levels, only after zooming in to level 14 or higher. In my app, I use three different tile maps sources for different zoom levels.

I need to clean up mo code a bit before sharing. However, below are the map definitions I have used. The beta-site is stripped down version already. I am using React and Mobx, but this stripped down version does not seem to rely on those. The include report can be found in here: https://beta--karttahimmeli.netlify.app/report.html

I have noticed that even if I disable the zoom slider control, but still leave the css layout code as it is in the beta site, I can replicate the issue. I mean if I use an empty space between the zoom in and zoom out buttons with that default color changing mouse top over tooltip etc, I can still replicate the issue. So the control does not even need to be a functional one to cause the issue. On the other hand, in my real app, I have got material-ui buttons located to higher z-layers over the map etc and they don't seem to cause any issues. 

The tile layer definitions used are:
```
var OSMLayer = new TileLayer({
      source: new OSM(),
      visible: true,
      maxZoom: 14
    });

 var mmlAvoinLayer = new TileLayer({
      source: new XYZ({
        url: 'https://avoin-karttakuva.maanmittauslaitos.fi/avoin/wmts/1.0.0/maastokartta/default/WGS84_Pseudo-Mercator/{z}/{y}/{x}.png',
        attributions: "© Maanmittauslaitos. Käyräväli 5m"
      }),
      projection: 'EPSG:3857',
      minZoom: 14,
      maxZoom: 16,
      opacity: 1,
      visible: true
    });

var pullautuskartta = new TileLayer({
      source: new XYZ({
        projection: 'EPSG:3857', //HERE IS THE DATA SOURCE PROJECTION
        url: 'https://wmts.mapant.fi/wmts_EPSG3857.php?z={z}&x={x}&y={y}',
        attributions: "© MapAnt.fi. Käyräväli 2.5m"
      }),
      visible: true,
      minZoom: 16,
    });
```

The difference seems to be that two tile sources are using projection calculation. Maybe that is causing some funny timing issues?

My temporary fix is this. Does not really do any harm for the scale bar, but obviously attribution links stop working.

```
#map .ol-attribution {
    pointer-events: none;
}

#map .ol-scale-bar  {
    pointer-events: none;
    bottom: 18px;
    }

```

**Comment by ahocevar** [comment]
It turns out that this not only affects touch gestures, but can also be reproduced with a mouse or trackpad:

1. Go to https://openlayers.org/en/latest/examples/simple.html
2. Pan the map with the mouse or trackpad, and release the mouse button or trackpad when the pointer is over the +/- zoom control. Now start dragging again somewhere else on the map and watch the map jump.

This is a regression introduced with #10496.

#11270 fixes this.
