### ISSUE TITLE
HERE Maps Example not working properly

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12040]
**Describe the bug**
The example using HERE map tiles has drop downs from which to choose. Those do not generate a working map view and throw errors in the console.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/here-maps.html
2. Click on any other display view that is offered by the drop down below the map (e.g."Normal Day Transit")
3. Open up the console which shows a list of 403s (screenshot included)

**Expected behavior**
The map is redrawn according to the choice that was made.

Tested and reproduced on Chrome, Firefox, Edge and Safari.
Opening one of those not-found-links leads to an endoint that says:

```json
{
"error": "Forbidden",
"error_description": "These credentials do not authorize access. Please contract your customer representative or email locationapi@here.com to discuss upgrading your account."
}
```

Maybe the key must be updated?

![Screen Shot 2021-02-16 at 16 50 47](https://user-images.githubusercontent.com/213803/108086895-28088c00-7077-11eb-9134-d792eb45ea27.png)

**Comment by mike-000** [comment]
Yes, the old app_id app_code pair is no longer working, and in the latest HERE API is replaced by an API key.  It has already been fixed by #11899  Working example at https://deploy-preview-11899--ol-site.netlify.app/examples/here-maps.html

**Comment by rowild** [comment]
Excellent! And beautiful! Thank you! closing the issue.

Are you, by any chance, the same mike who helped me out on gis.stackexchange.com?

**Comment by rowild** [comment]
Out of interest: are there any guidelines on when we can expect the documentation to be updated? This issue is still not available in the official examples...

**Comment by mike-000** [comment]
It is now working in `main` (the dev build) https://openlayers.org/en/main/examples/here-maps.html but not yet in `latest` (release version).

**Comment by philhitchman** [comment]
Hi, this issue appears to have re-surfaced. We have several sites where the maps are no longer appearing (e.g. https://hostunusual.com/destinations/austria/) and the above examples have also stopped working.

**Comment by mike-000** [comment]
https://hostunusual.com/destinations/austria/ is failing because it cannot load `ol.js` from jsdelivr  The code is using tiles from MapTiler.  To avoid dependency on other sites it would be better to download the `dist.zip` for the version you are using from https://github.com/openlayers/openlayers/releases and use it from your server.

**Comment by philhitchman** [comment]
Ah, OK thanks Mike. I will pass that on to my developer. Thanks for your 
assistance :)

Phil.
