### ISSUE TITLE
Importing GeoTIFF source causes compilation errors in Angular

### ISSUE THREAD

**Issue by javier-lopez-1s** [openlayers/openlayers#13924]
**Describe the bug**
I am using OpenLayers 6.15.1 in an Angular 14 application and when I import the source GeoTIFF I get the following compilation errors:

```
Error: node_modules/geotiff/dist-node/geotiffimage.d.ts:67:118 - error TS2304: Cannot find name 'Source'.
67     constructor(fileDirectory: any, geoKeys: any, dataView: DataView, littleEndian: boolean, cache: boolean, source: Source);

Error: node_modules/geotiff/dist-node/geotiffimage.d.ts:75:13 - error TS2304: Cannot find name 'Source'.
75     source: Source;

Error: node_modules/geotiff/dist-node/geotiffimage.d.ts:134:100 - error TS2304: Cannot find name 'AbstractDecoder'.
134     getTileOrStrip(x: number, y: number, sample: number, poolOrDecoder: import("./geotiff").Pool | AbstractDecoder, signal?: AbortSignal | undefined): Promise<ArrayBuffer>;
```

**To Reproduce**
1. `ng new test-app`
2. `cd test-app`
3. `npm install ol`
4. Add `import GeoTIFFSource from 'ol/source/GeoTIFF';` to app.component.ts
5. `ng build`

**Expected behavior**
No compilation errors.
Please confirm if this should be reported on the _geotiff_ repository instead.

**Comment by ahocevar** [comment]
This is an issue with geotiff.js, which the `GeoTIFF` source depends on. A quick cure would be to configure your `tsconfig.json` to have `skipLibCheck: true` in `compilerOptions`.

**Comment by javier-lopez-1s** [comment]
Thanks @ahocevar. I will create an issue on the _geotiff_ repository.

**Comment by ahocevar** [comment]
That issue was already fixed in geotiff.js (see https://github.com/geotiffjs/geotiff.js/pull/295), but it has not been released yet.

**Comment by mkelly1495** [comment]
This issue still exists with openlayers `v7.1.0`. The last comment on this issue was back in August. Is there a fix for this that doesn't require me to set `skipLibCheck: true` in `compilerOptions`?

**Comment by mkelly1495** [comment]
Just checked [npmjs](https://www.npmjs.com/package/geotiff) and it says the last release of geotiff was 7 months ago even though [this](https://github.com/geotiffjs/geotiff.js/pull/295) issue claims they did a release 29 days ago. I posted a message on geotiff asking why there was no release.

**Comment by mkelly1495** [comment]
GeoTIFF has released the build containing the fix for the above (`2.0.6`). Please update openlayers to use the new [version](https://www.npmjs.com/package/geotiff/v/2.0.6).
