### ISSUE TITLE
WebGL point feature hover detection inconsistent in example

### ISSUE THREAD

**Issue by jasontk19** [openlayers/openlayers#14836]
**Describe the bug**
When using the example code found on the [WebGL Points Layer example page](https://openlayers.org/en/latest/examples/webgl-points-layer.html), it can be seen that hovering over a point causes a flickering of the point color due to a sort of race condition between setting the `hover` state to `0` or `1`. Sometimes when the pointer stops, the state is `1` and sometimes it is `0`. Here is an example GIF of this behavior. 
![flicker](https://github.com/openlayers/openlayers/assets/1480000/5d7d928e-7f04-443f-b6ae-5d5c562705f3)
Here is the relevant code snippet that is responding to mouse interaction:

```
map.on('pointermove', function (ev) {
  if (selected !== null) {
    selected.set('hover', 0);
    selected = null;
  }

  map.forEachFeatureAtPixel(ev.pixel, function (feature) {
    feature.set('hover', 1);
    selected = feature;
    return true;
  });
});
```

**Expected behavior**
Ideally, any time the mouse pointer is over the feature, the feature would be marked as hovered. We would like to be able to show an overlay tooltip when hovering over a point like this but, this sort of flickering is particularly exaggerated when doing so. Is there a known better approach to consistently detecting hover on a WebGL feature like this?

**Comment by jasontk19** [comment]
Here you can see the issue is exaggerated by trying to show a tooltip overlay when a point is hovered:
![flicker_tooltip](https://github.com/openlayers/openlayers/assets/1480000/a9f6ebf4-1180-4e99-8303-876e849f81f6)

**Comment by mike-000** [comment]
Hit detection has been reworked since the last release.  Do you see the problem in the dev version https://openlayers.org/en/main/examples/webgl-points-layer.html ?

**Comment by jahow** [comment]
In this example highlighting the feature under the cursor is done by changing the feature `hover` property, which triggers a complete rebuild of the whole layer. This could be improved to something more efficient quite easily, maybe with something like this:
```js
map.on('pointermove', function (ev) {
  if (selected !== null) {
    selected.set('hover', 0);
    selected = null;
  }
  let found = null;
  map.forEachFeatureAtPixel(ev.pixel, function (feature) {
    return found = feature;
    return true;
  });
});
```

I'm marking this as "PR accepted", if @jasontk19 or anyone feels like working on it.

**Comment by mike-000** [comment]
if (selectedRef.current && found !== selectedRef.current) {
      selectedRef.current.set('hover', 0);
      selectedRef.current = null;
    }
    if (!found) {
      overlayRef.current.setPosition(undefined);
      return;
    }


should reduce the flickering of the overlay.

**Comment by mike-000** [comment]
> I am seeing some unexpected behavior with hit detection as well.

That should be fixed by #15340.  As it is not yet included in a release you will need to use the dev version to include the fix.

**Comment by sebastiankrll** [comment]
I still have the exact same problem like @jasontk19, but with the latest version 9.2.4

When logging the returned feature by map.forEachFeatureAtPixel(), it sometimes randomly returns undefined for a couple of iterations, even though the mouse is on top of a marker.

**Comment by sebastiankrll** [comment]
My somewhat dirty solution for now (but it works):

Introduce a counter to ignore falsely returned `undefined` values from `map.forEachFeatureAtPixel`.

```javascript
let counter = 0

const handleHover = (event) => {
    const feature = map.forEachFeatureAtPixel(event.pixel, (feature) => feature)

    if (!feature) {
        if (counter < 10) {
            counter++
            return
        } else {
            counter = 0
        }
    }

    [...]
```
