### ISSUE TITLE
ol.style.Circle high DPI support

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#1574]

**Comment by ahocevar** [comment]
@fredj Looking at the examples, it seems to me that this is fixed. Can you please check?

**Comment by fredj** [comment]
It's not fixed: https://github.com/openlayers/ol3/blob/master/src/ol/style/circlestyle.js#L150-L152
The `pixelRatio` value is ignored

**Comment by djibarian** [comment]
Does this mean is not going to fix it? Circles look blurry on retina displays where everything else is sharp. This makes Circle totally unusable.
