### ISSUE TITLE
Disabled hit detection WebGL Renderer problem

### ISSUE THREAD

**Issue by GraNaTic** [openlayers/openlayers#16405]
**Describe the bug**
When enabling a layer containing polygons and any WebGL layer containing points, a WebGL error occurs:
[.WebGL-0x77b403e75b00] GL_INVALID_OPERATION: Error: 0x00000502, in ..\..\third_party\angle\src\libANGLE\renderer\d3d\VertexDataManager.cpp, rx::VertexDataManager::reserveSpaceForAttrib:523. Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.

The issue also arises when enabling a polygon layer 'Aerodrome hubs' styled as 'tma' along with any other polygon layer.

**To Reproduce**

1. Create an OpenLayers map with WebGL layers and multiple geometries.

```
export class WebGLLayer extends Layer {
  constructor(options) {
    super(options);
  }

  createRenderer() {
    const style = getLayerStyle(this.get('layerType'));
    this.set('style', style);
    return new WebGLVectorLayerRenderer(this, {
      className: this.getClassName(),
      style,
      disableHitDetection: true
    });
  }
}
```

2. Add a polygon layer with the following style:

```
fir: {
    'fill-color': 'rgba(0,175,0,0.3)',
    'stroke-color': ['match', ['get', 'highlighted'], 1,
      'rgba(255, 0, 0, 1)',
      'rgba(0,175,0,0.6)'
    ],
    'stroke-width': 2,
}
```

3. Add point layers styled as:

```
landingpad: {
    'circle-radius': [
      'interpolate',
      ['linear'],
      ['zoom'],
      4, 4,
      15, 15,
    ],
    'circle-fill-color': ['match', ['get', 'highlighted'], 1,
      'rgba(255,255,0,1)',
      'rgba(94,220,31,0.7)'
    ],
    'circle-opacity': 0.9,
},
pod: {
    'shape-points': 3,
    'shape-radius': [
      'interpolate',
      ['linear'],
      ['zoom'],
      4, 4,
      15, 15,
    ],
    'shape-fill-color': ['match', ['get', 'highlighted'], 1,
      'rgba(255,255,0,1)',
      'rgba(255,255,255,1)'
    ],
    'shape-stroke-color': 'rgba(0,0,0,1)',
    'shape-stroke-width': 1,
    'shape-rotate-with-view': false,
},
aerodrome: {
    'circle-fill-color': ['match', ['get', 'highlighted'], 1,
      'rgba(255,255,0,1)',
      'rgba(255, 0, 0, 0.7)'
    ],
    'circle-radius': [
      'interpolate',
      ['linear'],
      ['zoom'],
      4, 4,
      15, 15,
    ],
    'circle-opacity': 0.9,
}
```
4. Alternatively, use multiple polygon layers styled like this:

```
tma: {
    'fill-color': 'rgba(255,255,0,0.3)',
    'stroke-color': ['match', ['get', 'highlighted'], 1,
      'rgba(255, 0, 0, 1)',
      'rgba(0,0,136,1)'
    ],
    'stroke-width': 2,
},
ra: {
    'fill-color': 'rgba(208,247,228,0.3)',
    'stroke-color': ['match', ['get', 'highlighted'], 1,
      'rgba(255, 0, 0, 1)',
      'rgba(1,1,1,1)'
    ],
    'stroke-width': 2,
}
```
Observe the WebGL error in the console during rendering (video shows webgl working process with disabled hitDetection).

https://github.com/user-attachments/assets/14b826e4-2ab9-4066-8982-406ce9f69e2c

**Expected behavior**
The map should render all layers and geometries without errors, regardless of the combination of polygon and point layers (video shows webgl working process with enabled hitDetection).

https://github.com/user-attachments/assets/fcbd59c7-bc2f-424d-bba9-dfd18572624b

**Environment**

OpenLayers Version: 10.2.1
Browser: Chrome 131.0.6778.86
OS: Windows 11

**Additional**
Preliminary observations suggest that disabling hitDetection for WebGL layers significantly improves the smoothness of map panning and interactions. However, this configuration appears to contribute to the occurrence of the described WebGL error when multiple geometry types are rendered simultaneously.

**Comment by GraNaTic** [comment]
I am already using separate instances of the WebGLLayer class for each style in my implementation. During experiments, I also tried creating a separate class for each style, but this approach, as expected, had no effect on the results of my experiments.

**Comment by nssang00** [comment]
https://github.com/openlayers/openlayers/blob/f274df225801a26532302eb630f8842ec71f7886/src/ol/render/webgl/VectorStyleRenderer.js#L202-L211

After Change
```javascript
    const hitDetectionAttributes = this.hitDetectionEnabled_
      ? {
          hitColor: {
            callback() {
              return colorEncodeId(this.ref, tmpColor);
            },
            size: 4,
          },
        }
      : { hitColor: { callback: () => [0, 0, 0, 0], size: 4 } };
```
The a_prop_hitColor value required in the vertex shader may be missing or insufficient. In this case, the **Vertex Buffer** in WebGL may be allocated with a smaller size than expected, or the vertex data may not be filled properly, resulting in a vertex buffer error.
The cleanest way is to remove the variables and assignments related to hitColor from getSymbolVertexShader and getSymbolFragmentShader in ShaderBuilder.js.
However, since it only works when 'u_hitDetection' is greater than 0, putting in the value `{ hitColor: { callback: () => [0, 0, 0, 0], size: 4 } }` will not work.

**Comment by GraNaTic** [comment]
Actually, changing {} value in the 211 line of the VectorStyleRenderer to the { hitColor: { callback: () => [0, 0, 0, 0], size: 4 } }; is solved that bug!

**Comment by jahow** [comment]
Hi @GraNaTic , I tried picking up this issue again but could not reproduce it locally. Can you please confirm that you still see this happening, especially when using the `WebGLVectorLayer` class? Thank you!

**Comment by GraNaTic** [comment]
Greetings @jahow ! I sincerely apologize for responding with such a delay! Yes, the errors are still occurring - I just checked my first implementation of the WebGLLayer class, then tried to use the new built-in WebGLVectorLayer implementation with this configuration:
```javascript
layer = new WebGLVectorLayer({
          source: vectorSource,
          layerName: type,
          airspaceStructureLayer: true,
          customMinZoom: 10,
          style: styles[type],
          disableHitDetection: true,
        });
```
And I encountered the same problem. Are you sure that during problem reproduction you set disableHitDetection: true?

**Comment by jahow** [comment]
Ok, thanks for responding. I have been trying to reproduce this bug for a while and never managed to, I suspect that it is related to having several WebGL layers and maybe switching visibility between them.

Can you please tell me:
* How many layers you are rendering on the map when the error happens?
* The styles used for those layers?

And even better, give me a sample of data that would let me reproduce the error locally. Thank you!

**Comment by GraNaTic** [comment]
Hi @jahow, I render up to 46 layers simultaneously on a map using WebGLVectorLayer. Each layer contains features with a single geometry type. I conducted a small experiment and discovered that the problem occurs when displaying more than two layers simultaneously - regardless of which geometries are used in these layers. The problem doesn't arise until the visibility of more than 2 layers is activated. 
The problem disappears if you follow nssang00's advice in  [#](https://github.com/openlayers/openlayers/issues/16405#issuecomment-2500906970) and change some source code in VectorStyleRenderer. 
Here's the data and styles to reproduce the problem locally.

```javascript
export const styles = {
    gc: {
      'fill-color': 'rgba(248, 111, 248, 0.1)',
      'stroke-color': ['match', ['get', 'highlighted'], 1, 'rgba(255,0,0,1)', 'rgba(148, 148, 148, 0.4)'],
      'stroke-width': 2,
    },
    zc: {
      'fill-color': 'rgba(52, 64, 241, 0.1)',
      'stroke-color': ['match', ['get', 'highlighted'], 1, 'rgba(255,0,0,1)', 'rgba(148, 148, 148, 0.4)'],
      'stroke-width': 2,
    },
    fir: {
      'fill-color': 'rgba(1, 241, 1, 0.1)',
      'stroke-color': ['match', ['get', 'highlighted'], 1, 'rgba(255,0,0,1)', 'rgba(148, 148, 148, 0.4)'],
      'stroke-width': 2,
    },
    default: {
      'stroke-width': ['interpolate', ['linear'], ['resolution'], 800, 2, 2300, 1],
      'stroke-color': [
        'match',
        ['get', 'highlighted'],
        1,
        'rgba(255, 0, 0, 1)',
        'rgba(24, 86, 34, 0.7)',
      ],
      'stroke-line-cap': 'butt',
    },
  };
```

[fir.json](https://github.com/user-attachments/files/19732320/fir.json)
[gc.json](https://github.com/user-attachments/files/19732321/gc.json)
[zc.json](https://github.com/user-attachments/files/19732319/zc.json)

**Comment by jahow** [comment]
Thank you so much! I'll look into it.

**Comment by jahow** [comment]
Hi again @GraNaTic, unfortunately I still can't reproduce the issue. This is a codesandbox link that I've used to try and reproduce it: https://codesandbox.io/p/sandbox/j2gt97

I ran this in an emulator with the specs you described originally (windows 11, chrome 131), also made sure that the ANGLE renderer was used, but no error.

Coud you please let me know if the error shows up in the codesandbox above? If yes, this must be hardware related somehow. If not, I'll need your help to set up a reliable reproduction case in codesandbox.

Thank you for your help!

**Comment by GraNaTic** [comment]
Greetings @jahow! I checked your example in CodeSandbox and initially couldn't reproduce the bug. However, after removing the "vectorLayer" with loaded ecoregions.json from the map layers array, I was able to reproduce the issue. Therefore, try removing the "vectorLayer" from the map layers array at line 128 - if the problem still doesn't reproduce in the preview window, try opening the preview in a separate browser tab.

Good luck!

**Comment by jahow** [comment]
@GraNaTic can you please tell me again which system you are using? I have been trying to reproduce with [this codesandbox](https://codesandbox.io/p/sandbox/webgl-vector-layer-forked-xzvkx5) (preview [here](https://xzvkx5.csb.app/)) which I adjusted as you suggested, but still can't see the bug happening. I tried running this preview on a windows 11 system with chrome 31 to no avail.

**Comment by GraNaTic** [comment]
@jahow the bug is reproducing on my Windows 10 Chrome 135.0.7049.116 with your preview. 
My system is running on Intel Core i5-8600

**Comment by GraNaTic** [comment]
I have also tested your preview on
- laptop with discrete Nvidia GPU and Intel CPU, OS Windows 11, Chrome;
- pc with discrete GTX 210 and Intel CPU, OS Windows 7, Chrome and Firefox;
- my pc in Firefox;
and the bug was reproduced at each system

**Comment by jahow** [comment]
I think this is fixed by https://github.com/openlayers/openlayers/pull/16840, it would be great if someone else could look at it and confirm that it works (it is fixed on my emulated system). Thanks!

**Comment by johnnyelwailer** [comment]
@jahow  Hey, I just randomlyencountered the same issue as I disabled hit detection. I then updated to the build of the current main branch, and the error disappeared. Works as expected, thanks for the fix!

**Comment by jahow** [comment]
Thank you for the confirmation @johnnyelwailer

**Comment by GraNaTic** [comment]
+, fixed problem for me too
