### ISSUE TITLE
Getting Error: Cannot read properties of null (reading 'globalAlpha') when setting opacity on a WFS-layer

### ISSUE THREAD

**Issue by nilsmeinhard** [openlayers/openlayers#16878]
**Describe the bug**
We just upgraded openlayers to 10.5.0 from 10.4.0 and then we noticed that we got the error mentioned in the title
on row 258 in the file webpack://span/node_modules/ol/renderer/canvas/VectorLayer.js

**To Reproduce**
1. Create a VectorLayer object that have some features
2. Call the method setOpacity on the layer object with a value different from 1, for example 0.5
3. See error, maybe you have to do some panning or zooming to get the features in the layer to rerender

**Expected behavior**
The features should be drawn with some opacity. When we downgraded to Openlayers 10.4.0 was the error gone

**Comment by TheWeirdDev** [comment]
I'm also getting the same exact error

**Comment by ahocevar** [comment]
Alright, I think this has been fixed already. Can you please `npm install ol@dev` and try again?

**Comment by nilsmeinhard** [comment]
Yes, I tried that now...but the error remains... One thing I haven't mentioned is that we have a lot more layers active and visible. Could it be that that is causing the problem?

**Comment by ahocevar** [comment]
Hard to tell without being able to reproduce.

**Comment by cristianmadularu** [comment]
Any chance we could get a new release containing this fix? Thank you!

**Comment by ahocevar** [comment]
I'll try to find some time to cut a release this weekend. In the meantime, `npm install ol@dev` to get a version where this is fixed already.

**Comment by cristianmadularu** [comment]
Thank you @ahocevar. I'll wait for the official release. I have currently patched the version locally.
