### ISSUE TITLE
Chrome mobile, custom build, pan zoom broken

### ISSUE THREAD

**Issue by fperucic** [openlayers/openlayers#6301]
Google chrome released a new mobile version. In it, my custom build did not work, and it worked in FF. Pan and zoom were broken.

The solution to my problem was to add `externs/closure-compiler.js` to the `compile.externs` tag in the custom json file. I don't know if this is expected behaviour, but I'm submiting an issue because in the previous versions it worked without `externs/closure-compiler.js`.

Regards

**Comment by fperucic** [comment]
sry, here is some more info. I was having issues on the android 6.0.1, S6. It was also tested on some other newer devices also the same issue. however on s3 it worked normally.

**Comment by sookoll** [comment]
Can confirm. Chrome on Android both 6.0.1 on Nexus 7 and 5.1.1 on Sony Z1 compact. Unable to pan and zoom also zooms entire page.

**Comment by probins** [comment]
@fredj you're the expert on this. AFAICS it looks like both the issues you raised in your PRs to the compiler have been resolved, but [another issue](https://github.com/google/closure-compiler/issues/1763) meant that w3c_pointer_events got left out. As this is also now fixed in the latest compiler version, this problem should go away once we update to that. Then `externs/closure-compiler.js` shouldn't be needed any more.

In the meantime, I would say it's better to always include `externs/closure-compiler.js` in custom builds.

**Comment by fredj** [comment]
@fperucic are you using the latest version of the compiler?

And yes, you should always include `externs/closure-compiler.js` in your build

**Comment by fperucic** [comment]
I've just pulled the latest ol version, and updated the libs with `npm install`, and the issue is still present.

**Comment by probins** [comment]
closure-util is not yet using the latest compiler version - see #6294

**Comment by probins** [comment]
the custom builds tutorial is currently inconsistent on whether `externs/closure-compiler.js` should be present or not. With #6294, the file is no longer needed, but the PR is proposing keeping it as an empty file. In which case, I think the custom builds tutorial should be changed to say that this file, like `oli.js` and `olx.js`, should always be included in build config files. I can submit a PR for this if people agree that this is the way forward. The alternative would be to delete the file and remove it from build configs and tutorials.
